/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\Christmas Scene.glb -o src/components/ChristmasScene.tsx -k -K -r public 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    group1182067444: THREE.Mesh;
    group226490541: THREE.Mesh;
    group1825349058: THREE.Mesh;
    group1185238801: THREE.Mesh;
    group470038334: THREE.Mesh;
    group163784669: THREE.Mesh;
    group2122184233: THREE.Mesh;
    group298071967: THREE.Mesh;
    group1627010098: THREE.Mesh;
    group1543725654: THREE.Mesh;
    group752705454: THREE.Mesh;
    group807575922: THREE.Mesh;
    group2140374999: THREE.Mesh;
    group886140121: THREE.Mesh;
    group1104831192: THREE.Mesh;
    group1322971704: THREE.Mesh;
    group1777620526: THREE.Mesh;
    group1202089842: THREE.Mesh;
    group723889153: THREE.Mesh;
    group230463646: THREE.Mesh;
    group901195029: THREE.Mesh;
    mesh538833904: THREE.Mesh;
    mesh538833904_1: THREE.Mesh;
    mesh87747359: THREE.Mesh;
    mesh87747359_1: THREE.Mesh;
    mesh2121597824: THREE.Mesh;
    mesh2121597824_1: THREE.Mesh;
    mesh508380244: THREE.Mesh;
    mesh508380244_1: THREE.Mesh;
    mesh607157812: THREE.Mesh;
    mesh607157812_1: THREE.Mesh;
    mesh1008840158: THREE.Mesh;
    mesh1008840158_1: THREE.Mesh;
    mesh1548616672: THREE.Mesh;
    mesh1548616672_1: THREE.Mesh;
    mesh1561280400: THREE.Mesh;
    mesh1561280400_1: THREE.Mesh;
    mesh764744278: THREE.Mesh;
    mesh764744278_1: THREE.Mesh;
    mesh1315834789: THREE.Mesh;
    mesh1315834789_1: THREE.Mesh;
    mesh1720019047: THREE.Mesh;
    mesh1720019047_1: THREE.Mesh;
    mesh644515519: THREE.Mesh;
    mesh644515519_1: THREE.Mesh;
    mesh1375441840: THREE.Mesh;
    mesh1375441840_1: THREE.Mesh;
    mesh1574142308: THREE.Mesh;
    mesh1574142308_1: THREE.Mesh;
    mesh429496213: THREE.Mesh;
    mesh429496213_1: THREE.Mesh;
    mesh328824509: THREE.Mesh;
    mesh328824509_1: THREE.Mesh;
    mesh211977916: THREE.Mesh;
    mesh211977916_1: THREE.Mesh;
    mesh314560661: THREE.Mesh;
    mesh314560661_1: THREE.Mesh;
    mesh1328776369: THREE.Mesh;
    mesh1328776369_1: THREE.Mesh;
    mesh2058909209: THREE.Mesh;
    mesh2058909209_1: THREE.Mesh;
    mesh141820479: THREE.Mesh;
    mesh141820479_1: THREE.Mesh;
    mesh491579945: THREE.Mesh;
    mesh491579945_1: THREE.Mesh;
    mesh724556219: THREE.Mesh;
    mesh724556219_1: THREE.Mesh;
    mesh441733838: THREE.Mesh;
    mesh441733838_1: THREE.Mesh;
    group984652469: THREE.Mesh;
    group2036306786: THREE.Mesh;
    group923980669: THREE.Mesh;
    group761526700: THREE.Mesh;
    group1079565243: THREE.Mesh;
    group953213941: THREE.Mesh;
    group1385247711: THREE.Mesh;
    group434759994: THREE.Mesh;
    group648883559: THREE.Mesh;
    group1060669948: THREE.Mesh;
    group2002524216: THREE.Mesh;
    group726386786: THREE.Mesh;
    group1435811549: THREE.Mesh;
    group1613833146: THREE.Mesh;
    group1636433310: THREE.Mesh;
    group1661901607: THREE.Mesh;
    group1570340538: THREE.Mesh;
    group206984859: THREE.Mesh;
    group1860298104: THREE.Mesh;
    group1752288573: THREE.Mesh;
    group1273799144: THREE.Mesh;
    group181998817: THREE.Mesh;
    group1631567232: THREE.Mesh;
    group1590615580: THREE.Mesh;
    group1146172575: THREE.Mesh;
    group1828994263: THREE.Mesh;
    group227775135: THREE.Mesh;
    group714754567: THREE.Mesh;
    group999448014: THREE.Mesh;
    group624012494: THREE.Mesh;
    group1582480112: THREE.Mesh;
    group518788781: THREE.Mesh;
    group1350120884: THREE.Mesh;
    group1860981197: THREE.Mesh;
    group1526255069: THREE.Mesh;
    group1223032240: THREE.Mesh;
    group1882110088: THREE.Mesh;
    group1940428686: THREE.Mesh;
    group1974861947: THREE.Mesh;
    group570892524: THREE.Mesh;
    group1808676734: THREE.Mesh;
    group32000834: THREE.Mesh;
    group1341509323: THREE.Mesh;
    group402167689: THREE.Mesh;
    group1354072142: THREE.Mesh;
    group66974734: THREE.Mesh;
    group1171633533: THREE.Mesh;
    group1896940791: THREE.Mesh;
    group1797670541: THREE.Mesh;
    group1935316782: THREE.Mesh;
    group746893042: THREE.Mesh;
    group1962695053: THREE.Mesh;
    group410577068: THREE.Mesh;
    group1742043426: THREE.Mesh;
    group592434553: THREE.Mesh;
    group1183198297: THREE.Mesh;
    group720666589: THREE.Mesh;
    group583708557: THREE.Mesh;
    group759797947: THREE.Mesh;
    group556862698: THREE.Mesh;
    group743694313: THREE.Mesh;
    group1142129630: THREE.Mesh;
    group185461546: THREE.Mesh;
    group42186468: THREE.Mesh;
    group294472650: THREE.Mesh;
    group1455824762: THREE.Mesh;
    group1112066603: THREE.Mesh;
    group1663753921: THREE.Mesh;
    group1715099654: THREE.Mesh;
    group816619190: THREE.Mesh;
    group1076503986: THREE.Mesh;
    group148684799: THREE.Mesh;
    group622442755: THREE.Mesh;
    group1397951495: THREE.Mesh;
    group762690583: THREE.Mesh;
    group263291863: THREE.Mesh;
    group1406835247: THREE.Mesh;
    group526852741: THREE.Mesh;
    group1776577298: THREE.Mesh;
    group1219206969: THREE.Mesh;
    group2109363361: THREE.Mesh;
    group1529005715: THREE.Mesh;
    group52695559: THREE.Mesh;
    group847274129: THREE.Mesh;
    group2145557849: THREE.Mesh;
    group884409437: THREE.Mesh;
    group92471742: THREE.Mesh;
    group1114439672: THREE.Mesh;
    group249788012: THREE.Mesh;
    group1763915758: THREE.Mesh;
    group1571551701: THREE.Mesh;
    group484289719: THREE.Mesh;
    group1337831525: THREE.Mesh;
    group2069368978: THREE.Mesh;
    group109114973: THREE.Mesh;
    mesh1301494852: THREE.Mesh;
    mesh1301494852_1: THREE.Mesh;
    mesh1301494852_2: THREE.Mesh;
    mesh612001310: THREE.Mesh;
    mesh612001310_1: THREE.Mesh;
    mesh195235000: THREE.Mesh;
    mesh195235000_1: THREE.Mesh;
    mesh930013895: THREE.Mesh;
    mesh930013895_1: THREE.Mesh;
    mesh2045374356: THREE.Mesh;
    mesh2045374356_1: THREE.Mesh;
    mesh2045374356_2: THREE.Mesh;
    mesh94046777: THREE.Mesh;
    mesh94046777_1: THREE.Mesh;
    mesh1631516506: THREE.Mesh;
    mesh1631516506_1: THREE.Mesh;
    mesh1902912203: THREE.Mesh;
    mesh1902912203_1: THREE.Mesh;
    mesh1902912203_2: THREE.Mesh;
    mesh204043792: THREE.Mesh;
    mesh204043792_1: THREE.Mesh;
    mesh1715402553: THREE.Mesh;
    mesh1715402553_1: THREE.Mesh;
    mesh1715402553_2: THREE.Mesh;
    mesh1398461394: THREE.Mesh;
    mesh1398461394_1: THREE.Mesh;
    mesh1398461394_2: THREE.Mesh;
    mesh535900711: THREE.Mesh;
    mesh535900711_1: THREE.Mesh;
    mesh784588934: THREE.Mesh;
    mesh784588934_1: THREE.Mesh;
    mesh1629957296: THREE.Mesh;
    mesh1629957296_1: THREE.Mesh;
    mesh385402332: THREE.Mesh;
    mesh385402332_1: THREE.Mesh;
    mesh321737220: THREE.Mesh;
    mesh321737220_1: THREE.Mesh;
    mesh137213253: THREE.Mesh;
    mesh137213253_1: THREE.Mesh;
    mesh1225141938: THREE.Mesh;
    mesh1225141938_1: THREE.Mesh;
    mesh2100967039: THREE.Mesh;
    mesh2100967039_1: THREE.Mesh;
    mesh2093051608: THREE.Mesh;
    mesh2093051608_1: THREE.Mesh;
    mesh2093051608_2: THREE.Mesh;
    mesh2093051608_3: THREE.Mesh;
    mesh2093051608_4: THREE.Mesh;
    mesh2093051608_5: THREE.Mesh;
    mesh2093051608_6: THREE.Mesh;
    mesh2093051608_7: THREE.Mesh;
    group1460597670: THREE.Mesh;
    group1730544535: THREE.Mesh;
    group408486769: THREE.Mesh;
    group1853513446: THREE.Mesh;
    group712010833: THREE.Mesh;
    group1148163483: THREE.Mesh;
    group1201418244: THREE.Mesh;
    group589212133: THREE.Mesh;
    group1101788192: THREE.Mesh;
    group2084536282: THREE.Mesh;
    group211991854: THREE.Mesh;
    group168521297: THREE.Mesh;
    group662837068: THREE.Mesh;
    group2117972645: THREE.Mesh;
    group1523545035: THREE.Mesh;
    group617498473: THREE.Mesh;
    group318134270: THREE.Mesh;
    group170466853: THREE.Mesh;
    group201871069: THREE.Mesh;
  };
  materials: {
    mat10: THREE.MeshStandardMaterial;
    mat20: THREE.MeshStandardMaterial;
    mat12: THREE.MeshStandardMaterial;
    mat8: THREE.MeshStandardMaterial;
    mat2: THREE.MeshStandardMaterial;
    mat21: THREE.MeshStandardMaterial;
    mat9: THREE.MeshStandardMaterial;
    mat14: THREE.MeshStandardMaterial;
    mat23: THREE.MeshStandardMaterial;
    mat7: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function ChristmasModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Christmas Scene.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          name="group1182067444"
          geometry={nodes.group1182067444.geometry}
          material={materials.mat10}
        />
        <mesh
          name="group226490541"
          geometry={nodes.group226490541.geometry}
          material={materials.mat10}
        />
        <mesh
          name="group1825349058"
          geometry={nodes.group1825349058.geometry}
          material={materials.mat10}
        />
        <mesh
          name="group1185238801"
          geometry={nodes.group1185238801.geometry}
          material={materials.mat10}
        />
        <mesh
          name="group470038334"
          geometry={nodes.group470038334.geometry}
          material={materials.mat10}
        />
        <mesh
          name="group163784669"
          geometry={nodes.group163784669.geometry}
          material={materials.mat20}
        />
        <mesh
          name="group2122184233"
          geometry={nodes.group2122184233.geometry}
          material={materials.mat12}
        />
        <mesh
          name="group298071967"
          geometry={nodes.group298071967.geometry}
          material={materials.mat8}
        />
        <mesh
          name="group1627010098"
          geometry={nodes.group1627010098.geometry}
          material={materials.mat12}
        />
        <mesh
          name="group1543725654"
          geometry={nodes.group1543725654.geometry}
          material={materials.mat2}
        />
        <mesh
          name="group752705454"
          geometry={nodes.group752705454.geometry}
          material={materials.mat12}
        />
        <mesh
          name="group807575922"
          geometry={nodes.group807575922.geometry}
          material={materials.mat2}
        />
        <mesh
          name="group2140374999"
          geometry={nodes.group2140374999.geometry}
          material={materials.mat12}
        />
        <mesh
          name="group886140121"
          geometry={nodes.group886140121.geometry}
          material={materials.mat8}
        />
        <mesh
          name="group1104831192"
          geometry={nodes.group1104831192.geometry}
          material={materials.mat8}
        />
        <mesh
          name="group1322971704"
          geometry={nodes.group1322971704.geometry}
          material={materials.mat8}
        />
        <mesh
          name="group1777620526"
          geometry={nodes.group1777620526.geometry}
          material={materials.mat8}
        />
        <mesh
          name="group1202089842"
          geometry={nodes.group1202089842.geometry}
          material={materials.mat12}
        />
        <mesh
          name="group723889153"
          geometry={nodes.group723889153.geometry}
          material={materials.mat2}
        />
        <mesh
          name="group230463646"
          geometry={nodes.group230463646.geometry}
          material={materials.mat12}
        />
        <mesh
          name="group901195029"
          geometry={nodes.group901195029.geometry}
          material={materials.mat12}
        />
        <group name="group538833904">
          <mesh
            name="mesh538833904"
            geometry={nodes.mesh538833904.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh538833904_1"
            geometry={nodes.mesh538833904_1.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group87747359">
          <mesh
            name="mesh87747359"
            geometry={nodes.mesh87747359.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh87747359_1"
            geometry={nodes.mesh87747359_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group2121597824">
          <mesh
            name="mesh2121597824"
            geometry={nodes.mesh2121597824.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh2121597824_1"
            geometry={nodes.mesh2121597824_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group508380244">
          <mesh
            name="mesh508380244"
            geometry={nodes.mesh508380244.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh508380244_1"
            geometry={nodes.mesh508380244_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group607157812">
          <mesh
            name="mesh607157812"
            geometry={nodes.mesh607157812.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh607157812_1"
            geometry={nodes.mesh607157812_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1008840158">
          <mesh
            name="mesh1008840158"
            geometry={nodes.mesh1008840158.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1008840158_1"
            geometry={nodes.mesh1008840158_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1548616672">
          <mesh
            name="mesh1548616672"
            geometry={nodes.mesh1548616672.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1548616672_1"
            geometry={nodes.mesh1548616672_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1561280400">
          <mesh
            name="mesh1561280400"
            geometry={nodes.mesh1561280400.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1561280400_1"
            geometry={nodes.mesh1561280400_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group764744278">
          <mesh
            name="mesh764744278"
            geometry={nodes.mesh764744278.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh764744278_1"
            geometry={nodes.mesh764744278_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1315834789">
          <mesh
            name="mesh1315834789"
            geometry={nodes.mesh1315834789.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1315834789_1"
            geometry={nodes.mesh1315834789_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1720019047">
          <mesh
            name="mesh1720019047"
            geometry={nodes.mesh1720019047.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1720019047_1"
            geometry={nodes.mesh1720019047_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group644515519">
          <mesh
            name="mesh644515519"
            geometry={nodes.mesh644515519.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh644515519_1"
            geometry={nodes.mesh644515519_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1375441840">
          <mesh
            name="mesh1375441840"
            geometry={nodes.mesh1375441840.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1375441840_1"
            geometry={nodes.mesh1375441840_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1574142308">
          <mesh
            name="mesh1574142308"
            geometry={nodes.mesh1574142308.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1574142308_1"
            geometry={nodes.mesh1574142308_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group429496213">
          <mesh
            name="mesh429496213"
            geometry={nodes.mesh429496213.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh429496213_1"
            geometry={nodes.mesh429496213_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group328824509">
          <mesh
            name="mesh328824509"
            geometry={nodes.mesh328824509.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh328824509_1"
            geometry={nodes.mesh328824509_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group211977916">
          <mesh
            name="mesh211977916"
            geometry={nodes.mesh211977916.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh211977916_1"
            geometry={nodes.mesh211977916_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group314560661">
          <mesh
            name="mesh314560661"
            geometry={nodes.mesh314560661.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh314560661_1"
            geometry={nodes.mesh314560661_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1328776369">
          <mesh
            name="mesh1328776369"
            geometry={nodes.mesh1328776369.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1328776369_1"
            geometry={nodes.mesh1328776369_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group2058909209">
          <mesh
            name="mesh2058909209"
            geometry={nodes.mesh2058909209.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh2058909209_1"
            geometry={nodes.mesh2058909209_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group141820479">
          <mesh
            name="mesh141820479"
            geometry={nodes.mesh141820479.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh141820479_1"
            geometry={nodes.mesh141820479_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group491579945">
          <mesh
            name="mesh491579945"
            geometry={nodes.mesh491579945.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh491579945_1"
            geometry={nodes.mesh491579945_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group724556219">
          <mesh
            name="mesh724556219"
            geometry={nodes.mesh724556219.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh724556219_1"
            geometry={nodes.mesh724556219_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group441733838">
          <mesh
            name="mesh441733838"
            geometry={nodes.mesh441733838.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh441733838_1"
            geometry={nodes.mesh441733838_1.geometry}
            material={materials.mat21}
          />
        </group>
        <mesh
          name="group984652469"
          geometry={nodes.group984652469.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group2036306786"
          geometry={nodes.group2036306786.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group923980669"
          geometry={nodes.group923980669.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group761526700"
          geometry={nodes.group761526700.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1079565243"
          geometry={nodes.group1079565243.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group953213941"
          geometry={nodes.group953213941.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1385247711"
          geometry={nodes.group1385247711.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group434759994"
          geometry={nodes.group434759994.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group648883559"
          geometry={nodes.group648883559.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1060669948"
          geometry={nodes.group1060669948.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group2002524216"
          geometry={nodes.group2002524216.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group726386786"
          geometry={nodes.group726386786.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1435811549"
          geometry={nodes.group1435811549.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1613833146"
          geometry={nodes.group1613833146.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1636433310"
          geometry={nodes.group1636433310.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1661901607"
          geometry={nodes.group1661901607.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1570340538"
          geometry={nodes.group1570340538.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group206984859"
          geometry={nodes.group206984859.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1860298104"
          geometry={nodes.group1860298104.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1752288573"
          geometry={nodes.group1752288573.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1273799144"
          geometry={nodes.group1273799144.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group181998817"
          geometry={nodes.group181998817.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1631567232"
          geometry={nodes.group1631567232.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1590615580"
          geometry={nodes.group1590615580.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1146172575"
          geometry={nodes.group1146172575.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1828994263"
          geometry={nodes.group1828994263.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group227775135"
          geometry={nodes.group227775135.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group714754567"
          geometry={nodes.group714754567.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group999448014"
          geometry={nodes.group999448014.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group624012494"
          geometry={nodes.group624012494.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1582480112"
          geometry={nodes.group1582480112.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group518788781"
          geometry={nodes.group518788781.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1350120884"
          geometry={nodes.group1350120884.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1860981197"
          geometry={nodes.group1860981197.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1526255069"
          geometry={nodes.group1526255069.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1223032240"
          geometry={nodes.group1223032240.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1882110088"
          geometry={nodes.group1882110088.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1940428686"
          geometry={nodes.group1940428686.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1974861947"
          geometry={nodes.group1974861947.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group570892524"
          geometry={nodes.group570892524.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1808676734"
          geometry={nodes.group1808676734.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group32000834"
          geometry={nodes.group32000834.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1341509323"
          geometry={nodes.group1341509323.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group402167689"
          geometry={nodes.group402167689.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1354072142"
          geometry={nodes.group1354072142.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group66974734"
          geometry={nodes.group66974734.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1171633533"
          geometry={nodes.group1171633533.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1896940791"
          geometry={nodes.group1896940791.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1797670541"
          geometry={nodes.group1797670541.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1935316782"
          geometry={nodes.group1935316782.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group746893042"
          geometry={nodes.group746893042.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1962695053"
          geometry={nodes.group1962695053.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group410577068"
          geometry={nodes.group410577068.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1742043426"
          geometry={nodes.group1742043426.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group592434553"
          geometry={nodes.group592434553.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1183198297"
          geometry={nodes.group1183198297.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group720666589"
          geometry={nodes.group720666589.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group583708557"
          geometry={nodes.group583708557.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group759797947"
          geometry={nodes.group759797947.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group556862698"
          geometry={nodes.group556862698.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group743694313"
          geometry={nodes.group743694313.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1142129630"
          geometry={nodes.group1142129630.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group185461546"
          geometry={nodes.group185461546.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group42186468"
          geometry={nodes.group42186468.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group294472650"
          geometry={nodes.group294472650.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1455824762"
          geometry={nodes.group1455824762.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1112066603"
          geometry={nodes.group1112066603.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1663753921"
          geometry={nodes.group1663753921.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1715099654"
          geometry={nodes.group1715099654.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group816619190"
          geometry={nodes.group816619190.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1076503986"
          geometry={nodes.group1076503986.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group148684799"
          geometry={nodes.group148684799.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group622442755"
          geometry={nodes.group622442755.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1397951495"
          geometry={nodes.group1397951495.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group762690583"
          geometry={nodes.group762690583.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group263291863"
          geometry={nodes.group263291863.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1406835247"
          geometry={nodes.group1406835247.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group526852741"
          geometry={nodes.group526852741.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1776577298"
          geometry={nodes.group1776577298.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1219206969"
          geometry={nodes.group1219206969.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group2109363361"
          geometry={nodes.group2109363361.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1529005715"
          geometry={nodes.group1529005715.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group52695559"
          geometry={nodes.group52695559.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group847274129"
          geometry={nodes.group847274129.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group2145557849"
          geometry={nodes.group2145557849.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group884409437"
          geometry={nodes.group884409437.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group92471742"
          geometry={nodes.group92471742.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1114439672"
          geometry={nodes.group1114439672.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group249788012"
          geometry={nodes.group249788012.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1763915758"
          geometry={nodes.group1763915758.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1571551701"
          geometry={nodes.group1571551701.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group484289719"
          geometry={nodes.group484289719.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1337831525"
          geometry={nodes.group1337831525.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group2069368978"
          geometry={nodes.group2069368978.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group109114973"
          geometry={nodes.group109114973.geometry}
          material={materials.mat21}
        />
        <group name="group1301494852">
          <mesh
            name="mesh1301494852"
            geometry={nodes.mesh1301494852.geometry}
            material={materials.mat9}
          />
          <mesh
            name="mesh1301494852_1"
            geometry={nodes.mesh1301494852_1.geometry}
            material={materials.mat10}
          />
          <mesh
            name="mesh1301494852_2"
            geometry={nodes.mesh1301494852_2.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group612001310">
          <mesh
            name="mesh612001310"
            geometry={nodes.mesh612001310.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh612001310_1"
            geometry={nodes.mesh612001310_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group195235000">
          <mesh
            name="mesh195235000"
            geometry={nodes.mesh195235000.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh195235000_1"
            geometry={nodes.mesh195235000_1.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group930013895">
          <mesh
            name="mesh930013895"
            geometry={nodes.mesh930013895.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh930013895_1"
            geometry={nodes.mesh930013895_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group2045374356">
          <mesh
            name="mesh2045374356"
            geometry={nodes.mesh2045374356.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh2045374356_1"
            geometry={nodes.mesh2045374356_1.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh2045374356_2"
            geometry={nodes.mesh2045374356_2.geometry}
            material={materials.mat14}
          />
        </group>
        <group name="group94046777">
          <mesh
            name="mesh94046777"
            geometry={nodes.mesh94046777.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh94046777_1"
            geometry={nodes.mesh94046777_1.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group1631516506">
          <mesh
            name="mesh1631516506"
            geometry={nodes.mesh1631516506.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1631516506_1"
            geometry={nodes.mesh1631516506_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group1902912203">
          <mesh
            name="mesh1902912203"
            geometry={nodes.mesh1902912203.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh1902912203_1"
            geometry={nodes.mesh1902912203_1.geometry}
            material={materials.mat9}
          />
          <mesh
            name="mesh1902912203_2"
            geometry={nodes.mesh1902912203_2.geometry}
            material={materials.mat10}
          />
        </group>
        <group name="group204043792">
          <mesh
            name="mesh204043792"
            geometry={nodes.mesh204043792.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh204043792_1"
            geometry={nodes.mesh204043792_1.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group1715402553">
          <mesh
            name="mesh1715402553"
            geometry={nodes.mesh1715402553.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1715402553_1"
            geometry={nodes.mesh1715402553_1.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh1715402553_2"
            geometry={nodes.mesh1715402553_2.geometry}
            material={materials.mat14}
          />
        </group>
        <group name="group1398461394">
          <mesh
            name="mesh1398461394"
            geometry={nodes.mesh1398461394.geometry}
            material={materials.mat14}
          />
          <mesh
            name="mesh1398461394_1"
            geometry={nodes.mesh1398461394_1.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh1398461394_2"
            geometry={nodes.mesh1398461394_2.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group535900711">
          <mesh
            name="mesh535900711"
            geometry={nodes.mesh535900711.geometry}
            material={materials.mat10}
          />
          <mesh
            name="mesh535900711_1"
            geometry={nodes.mesh535900711_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group784588934">
          <mesh
            name="mesh784588934"
            geometry={nodes.mesh784588934.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh784588934_1"
            geometry={nodes.mesh784588934_1.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group1629957296">
          <mesh
            name="mesh1629957296"
            geometry={nodes.mesh1629957296.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh1629957296_1"
            geometry={nodes.mesh1629957296_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group385402332">
          <mesh
            name="mesh385402332"
            geometry={nodes.mesh385402332.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh385402332_1"
            geometry={nodes.mesh385402332_1.geometry}
            material={materials.mat10}
          />
        </group>
        <group name="group321737220">
          <mesh
            name="mesh321737220"
            geometry={nodes.mesh321737220.geometry}
            material={materials.mat10}
          />
          <mesh
            name="mesh321737220_1"
            geometry={nodes.mesh321737220_1.geometry}
            material={materials.mat21}
          />
        </group>
        <group name="group137213253">
          <mesh
            name="mesh137213253"
            geometry={nodes.mesh137213253.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh137213253_1"
            geometry={nodes.mesh137213253_1.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group1225141938">
          <mesh
            name="mesh1225141938"
            geometry={nodes.mesh1225141938.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh1225141938_1"
            geometry={nodes.mesh1225141938_1.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group2100967039">
          <mesh
            name="mesh2100967039"
            geometry={nodes.mesh2100967039.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh2100967039_1"
            geometry={nodes.mesh2100967039_1.geometry}
            material={materials.mat8}
          />
        </group>
        <group name="group2093051608">
          <mesh
            name="mesh2093051608"
            geometry={nodes.mesh2093051608.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh2093051608_1"
            geometry={nodes.mesh2093051608_1.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh2093051608_2"
            geometry={nodes.mesh2093051608_2.geometry}
            material={materials.mat10}
          />
          <mesh
            name="mesh2093051608_3"
            geometry={nodes.mesh2093051608_3.geometry}
            material={materials.mat23}
          />
          <mesh
            name="mesh2093051608_4"
            geometry={nodes.mesh2093051608_4.geometry}
            material={materials.mat14}
          />
          <mesh
            name="mesh2093051608_5"
            geometry={nodes.mesh2093051608_5.geometry}
            material={materials.mat7}
          />
          <mesh
            name="mesh2093051608_6"
            geometry={nodes.mesh2093051608_6.geometry}
            material={materials.mat20}
          />
          <mesh
            name="mesh2093051608_7"
            geometry={nodes.mesh2093051608_7.geometry}
            material={materials.mat9}
          />
        </group>
        <mesh
          name="group1460597670"
          geometry={nodes.group1460597670.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1730544535"
          geometry={nodes.group1730544535.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group408486769"
          geometry={nodes.group408486769.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1853513446"
          geometry={nodes.group1853513446.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group712010833"
          geometry={nodes.group712010833.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1148163483"
          geometry={nodes.group1148163483.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1201418244"
          geometry={nodes.group1201418244.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group589212133"
          geometry={nodes.group589212133.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1101788192"
          geometry={nodes.group1101788192.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group2084536282"
          geometry={nodes.group2084536282.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group211991854"
          geometry={nodes.group211991854.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group168521297"
          geometry={nodes.group168521297.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group662837068"
          geometry={nodes.group662837068.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group2117972645"
          geometry={nodes.group2117972645.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1523545035"
          geometry={nodes.group1523545035.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group617498473"
          geometry={nodes.group617498473.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group318134270"
          geometry={nodes.group318134270.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group170466853"
          geometry={nodes.group170466853.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group201871069"
          geometry={nodes.group201871069.geometry}
          material={materials.mat21}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Christmas Scene.glb');
